spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dasguptasrinjay7@gmail.com
    password: cljz mqvf vkij xtkc
    properties:
        mail:
            smtp:
              auth: true
              starttls:
                enable: true
                trust: "*"
    protocol: smtp
application:
  security:
    jwt:
      secret-key: A5C598F68CD00A21B197B19EB336FA0A2C552F2D101AFEB94399189961C968D2
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: 8088